/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error-container": "#ffdad6",
        "surface": "#fbf8ff",
        "primary-fixed-dim": "#b8c3ff",
        "on-secondary": "#ffffff",
        "outline": "#757684",
        "inverse-on-surface": "#f2eff9",
        "surface-tint": "#124af0",
        "primary": "#0032b5",
        "surface-container-high": "#e9e7f0",
        "on-secondary-fixed": "#002113",
        "tertiary-container": "#805000",
        "surface-variant": "#e3e1ea",
        "surface-container-highest": "#e3e1ea",
        "on-surface": "#1a1b22",
        "on-primary-fixed": "#001356",
        "primary-fixed": "#dde1ff",
        "on-primary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#efedf6",
        "tertiary": "#603b00",
        "on-tertiary-fixed": "#2a1700",
        "secondary-fixed": "#6ffbbe",
        "on-primary-fixed-variant": "#0035be",
        "secondary": "#006c49",
        "on-secondary-container": "#00714d",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        "surface-container-low": "#f4f2fc",
        "outline-variant": "#c5c5d4",
        "on-tertiary-fixed-variant": "#653e00",
        "inverse-primary": "#b8c3ff",
        "secondary-fixed-dim": "#4edea3",
        "secondary-container": "#6cf8bb",
        "on-error": "#ffffff",
        "on-surface-variant": "#454652",
        "on-secondary-fixed-variant": "#005236",
        "on-background": "#1a1b22",
        "inverse-surface": "#2f3037",
        "surface-dim": "#dbd9e2",
        "on-primary-container": "#c8d0ff",
        "on-tertiary-container": "#ffc988",
        "tertiary-fixed": "#ffddb8",
        "surface-bright": "#fbf8ff",
        "background": "#fbf8ff",
        "tertiary-fixed-dim": "#ffb95f",
        "primary-container": "#0344ec",
        "error": "#ba1a1a"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
    },
  },
  plugins: [],
}
